### ISSUE TITLE
Case.net flow 

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#142]
1. If user answers `yes` on `id: Docket_introduction` (Information about the party section) they do not get presented with `id: how to login to Case net` (Using Case.net section) until much later.
2. After `id: Docket_introduction` (but before seeing `id: how to login to Case net`) user is presented with `id: caption - docket number and file date` but because user answered yes on `id: Docket_introduction` they are asked again for the same info via `docket_header` (no id on screen)
3. After `id: Docket_introduction` (but before seeing `id: how to login to Case net`) user is presented with `names of opposing parties` which is showing a screengrab from case net. The directions "the next tab to the right" seem out of place or out of order in this flow.
4. After `id: explain other case net uses` (Using Case.net section) the interview jumped back to `id: petition requirements - rent amount` (Information about the eviction section)

**Comment by tobyfey** [comment]
The `docket_available` variable gets called early when `petition_available` is False, because it won't be able to use id: names of opposing parties - petition and it will go looking for that block that has if: docket_available.

I made a conditional statement in the interview order earlier to ask about the docket before the docket review would get to any screens that calls it.

**Comment by tobyfey** [comment]
Awkward order when the pleading is not available

id: caption - docket number and file date
id: Docket_introduction - Do you want to use the docket
id: case type from docket - What kind of eviction case is this?
id: how to login to Case net - Getting started with case.net


id: caption - docket number and file date is weird because it is asked before the question about using case.net but it has instructions about finding it in case.net in an accordion.  I think this might be a better way to do it throughout the interview.

**Comment by tobyfey** [comment]
After the first question when you hit next, it puts you back to the original casenet overview page. instead of the next question about info from casenet. 

     Need a fix on this.

from St. Jean, Victoria C. <vcstjean@lsem.org> email

**Comment by tobyfey** [comment]
case.net picture comes up for id: any other opposing parties before i was asked about case.net

**Comment by tobyfey** [comment]
checked - flow looks good when there is a pleading and yes, will test for no pleading

**Comment by tobyfey** [comment]
flow looks good when no pleading
