### ISSUE TITLE
`id: caption - docket number and file date` Issues

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#185]
1. Remove `none of the above`
2. Write out what "AC" means

`required: False` makes it look like this question is not required (no red asterisk) but then if unanswered gets validation error to select "None of the above"

![Screen Shot 2023-05-17 at 10 40 44 AM](https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/assets/65858862/bfd1c6e3-3994-43a7-b687-bf2d87834d03)

https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/blob/7b0a52ed846fb0abebac7b600ca755705f422ec7/docassemble/MOHUDEvictionProject/data/questions/court_information.yml#L65

**Comment by tobyfey** [comment]
We use the AC just to make it look the same as what is on either the summons or the docket.  But this screen should  just be for the summons - we should get rid of the "or Case Type" in the label because that is for the docket.

Maybe we should move down the image of the summons to right about that question?

We could also use an image of just the Nature of Suit box?

**Comment by tobyfey** [comment]
includew in #190
