### ISSUE TITLE
`id: caption - docket number and file date` other option 

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#192]
No longer a fill in field if "Other"
![Screen Shot 2023-05-24 at 3 07 42 PM](https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/assets/65858862/2693ac36-93e5-436c-92fe-54e68f3bc395)

**Comment by miabonardi** [comment]
Also should there be a kickout if user selects only other option? currently none

**Comment by miabonardi** [comment]
We probably dont need it if it isn't used anywhere but my comment was mainly whether user should get a warning screen if they select other (they currently do not)

**Comment by tobyfey** [comment]
Could we get feedback if somebody picks Other to try to minimize that?  It would be helpful then, and it probably makes more sense to the user if it's there than if it's not.

I'm glad we found the broken logic.  I will test it more, because I had to change it in a number of places  (id: interview_order_eviction, id: docket review order, enabling the eviction answer attachment)
