### ISSUE TITLE
Skip `explanation_answer` page if UD case

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#368]

**Comment by tobyfey** [comment]
I made it so that including this page doesn't cause an error, and shows explanations for relevant defenses, although none of the unlawful detainer defenses are included.  Also using collapse_template() to make the answer easier.  I think there's a lot of value to seeing what defenses are in the answer before looking at the answer and the evidence list.
