### ISSUE TITLE
Test and proof edit text in motion interview, make list of other issues

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#574]
Run the file_a_motion.yml in the playground

Live site https://motenanthelp.org/resources/other-motions-for-eviction-cases/

**Comment by KelizaMcGuire** [comment]
| Interview point | Comment |
|--------|--------|
| About your case: “Which motions do you need?”| Should we add descriptions to the motion types? |
| About your landlord: “What is the name of _landlord_’s attorney?” | Has Case.net example but no link to search site for yourself. |
| Service method: “What is _attorney_’s/_landlord_'s address?”/“At what address will you serve _attorney_/_landlord_?” | Asks attorney/landlord address, then after selecting serve by mail or hand delivery immediately asks for the address you will serve them at in the next question. Could we condense this to one question or do we need the option for two different addresses? Alternatively, we could have the option to select an already entered address. |
| Your motions: Motion for Leave to File Responsive Pleadings: “Was there a reason you couldn’t get your response ready and file it on time?” | Should we add examples? | 
| Your motions: Motion to Shorten Time: “When is your trial date planned?” | This motion is still available to fill out despite stating there is no planned trial date earlier in the "Motion for Leave to File Responsive Pleadings" portion of the interview. Should we include a warning that the defendant might not need to fill this out in that case? |
| Your motion: Motion to Shorten Time: “Do you have any unfair reasons for making this request?” | Should we add an explanation for what is an unfair reason? |
| Your motion: Motion to Set Aside Judgement: "Why should the judge agree to cancel the earlier decision because of your request?" | Should we provide examples here? |
| Preview your Motion to Shorten Time | **Background (3)** says "Defendant’s counsel has had little time previously to submit any challenges to Plaintiff's petition." Even though the defendant selected no counsel and signature block states they are pro se. This seems to be triggered by the answers to "Do you have any unfair reasons for making this request?". |
| Review screen for Motion to Shorten Time | Clicking edit on "Do you have any unfair reasons for making this request?" just reloads the page to the top of the review screen instead of allowing you to edit the answer. |
| Preview your Motion for Leave to File Responsive Pleadings | In the **Authority and Argument** section of pdf there is an "emphasis added" declaration at the end of a quote, but nothing is in italics. (screenshot attached) |
| Review your answers: “Plaintiffs” | _landlord_ has no address listed in the review screen even when they have no attorney. Their attorney's address is listed next to the attorney's name if they have one. (screenshot attached) |
| Review your answers: “Defendants” | _defendant_ has no address listed on review screen. (screenshot attached) No option to edit the defendant's address in review. |
| General | Should we add an explanation of what consent from the landlord means to all questions asking if they have given consent? |
| General | We should add a link to Case.net when it is referenced in the interview. |

- Google address suggestions sometimes don't populate the address when clicked or remove the street number but add everything else.
     - It is possible this only happens with addresses that aren't real, but they are still selectable from the suggestions. When these aren't caught they populate the pdf without a street number.

- Error at Download, print, and file. It was able to find the correct court for preview motions before review.
     - Each attempt at continuing from the review screen ends with Error: KeyError: ‘court_address_and_operating_hours’ (screenshots attached)

<img width="730" alt="defendant counsel reference" src="https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/174150691/0301f96c-ce9c-4323-9144-c056ce54a205">
<img width="778" alt="emphasis added" src="https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/174150691/9924ae3f-0a45-43ae-8918-eaa4c5d85e5d">
<img width="695" alt="defendant review" src="https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/174150691/57b3961e-fd68-4752-bb35-16b42f136776">

<img width="706" alt="landlord review" src="https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/174150691/e3cbf8e4-3ebc-4855-8f55-67fcf235b418">
<img width="724" alt="landlord review with attorney" src="https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/174150691/681f42b8-3cf1-44be-933e-1a71e19eee0d">
<img width="1079" alt="error" src="https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/174150691/b4c5051a-3126-4680-848c-028d16023d86">
<img width="571" alt="error log" src="https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/174150691/e0f415d6-2698-4e77-8fbd-f8dc4d5f957e">
<img width="414" alt="last attempt" src="https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/174150691/11de3bcf-bf33-4690-99ef-f8555e24e781">
